apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-grgv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/test-rhtap-7-tenant/load-app-da2620c9-f9c6-4879-abb2-f2fde04e6d72/devfile-sample-python-basic-grgv@sha256:c72c81e7c2d45fcf6aadcace44777c605a22ec54c7064e909e90af11d343d6ec
        name: my-python
        resources: {}
status: {}
